version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=bitquery_pump
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - BITQUERY_API_KEY=${BITQUERY_API_KEY}

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bitquery_pump
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 